# Generated by Django 5.1.2 on 2024-10-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eShop', '0003_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='Product',
            new_name='product',
        ),
    ]
