# Generated by Django 5.1.3 on 2024-11-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eShop', '0005_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default='categoty_images/dafault.jpg', upload_to='categoty_images'),
        ),
    ]
